# Generated by Django 3.1.3 on 2020-11-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('child_details', models.TextField(blank=True, null=True)),
                ('file', models.ImageField(upload_to='files')),
            ],
        ),
    ]
